export const enum ReportType {
    BERITA_ACARA = 'berita_acara',
    NEWS_DETAIL = 'newsinfo_detail',
    NEWS_SUMMARY = 'newsinfo_summary',
    NPK_COUPON = 'tgp_coupon_per_npk',
    VIDEO_DETAIL = 'video_detail',
    VIDEO_SUMMARY = 'video_summary',
    CHANNEL_SEARCH = 'channel_setup_search',
    EVENT_SEARCH = 'event_setup_search',
    THINKWARE_SEARCH = 'thinkware_search',
    FEEDBACK = 'feedback',
    FEEDBACK_SEARCH = 'feedback_setup_search',
    CONTENT_SEARCH = 'content_setup_search',
    CULTURE_MAPPING_CELL_HO = 'mapping_cell_ho',
    CULTURE_COUNTERPART = 'counter_part_setup_search',
    CULTURE_MAPPING_AREA = 'mapping_area_search',
    LOOKUP_SEARCH = 'lookup_setup_search',
    TEMPLATE_USAGE = 'template_usage_feedback',
    TGP_SEARCH = 'tgp_upload_search',
    USER_SEARCH = 'user_setup_search',
    VIDEO_SEARCH = 'video_setup_search',
}
